### ISSUE TITLE
This repository is violating the MIT license of Foolbox

### ISSUE THREAD

**Issue by jonasrauber** [advboxes/AdvBox#59]
Dear authors of AdvBox,

I believe this repository is violating the [MIT license](https://github.com/bethgelab/foolbox/blob/0a726b56fec08a6063ce596db62c4a11875b054e/LICENSE) of [Foolbox](https://github.com/bethgelab/foolbox).

It seems that substantial parts of the code in this repository have been copied from [Foolbox v1](https://github.com/bethgelab/foolbox/tree/30555ddaff02cd3b09a7e1389451af7b7fd40c8c). You have added some modifications (renaming variables, adding and removing comments, rearranging code, etc.), but nevertheless the code is still based on and copied from Foolbox without adhering to the conditions of the MIT license (despite it's extremely permissive rules).

Ironically, in [this commit](https://github.com/advboxes/AdvBox/commit/e3cc17bc38e85e1c4b686c4f14ebaf7b5a314103) you even forgot to replace `foolbox` with `advbox`. And in both your [README](https://github.com/advboxes/AdvBox/blob/cb7f8437d25ab67f26682a05a2b717545337ebf6/README.md) and your [paper](https://arxiv.org/abs/2001.05574v4) you use sentences like "Advbox is a toolbox to generate adversarial examples that fool neural networks" or "Advbox: a toolbox to generate adversarial examples that fool neural networks" that are not just loosely inspired by Foolbox's orignal slogan "Foolbox is a Python toolbox to create adversarial examples that fool neural networks.".

I propose we resolve this issue by making the following changes:

1. You explicitly state in your README that AdvBox is based on Foolbox v1
2. You explicitly state in your paper that AdvBox is based on Foolbox v1
3. You add the Foolbox `bibtex` entry to your [How to cite](https://github.com/advboxes/AdvBox#how-to-cite) section
4. You update your LICENSE file by adding our copyright and license
5. You update the Copyright and License part at the top of all files that are based on Foolbox to include our copyright and license

**Comment by ezhonghawke** [comment]
AdvBox is a suite of tools for various purposes. One sub-component that implements the adversarial white-box attacks is based on Foolbox v1. To distinguish AdvBox from its sub-components, we renamed this sub-component as adversarialbox. 
To address the MIT LICENSE violation, here are what we've changed:
1. we explicitly stated in README that adversarialbox is based on Foolbox v1. 
2. we explicitly stated in our arxiv paper  that the adversarialbox is based on Foolbox v1. The changes will be reflected on the latest arxiv version.
3. we updated LICENSE file by adding MIT LICENSE.
4. we removed copyright and license part at the top of the affected files so that they follow the root LICENSE.
